### ISSUE TITLE
The book often refers to Perl 6 as “Perl”

### ISSUE THREAD

**Issue by AlexDaniel** [LaurentRosenfeld/thinkperl6#3]
For example:

> 3. In math notation, leading zeros are OK, as in 02. What happens if you try this in Perl?

what Perl?

I think it should say

> 3. In math notation, leading zeros are OK, as in 02. What happens if you try this in Perl 6?

And it seems that this issue appears many times throughout the book.

**Comment by LaurentRosenfeld** [comment]
Yeah, I understand your point, but I have decided very early that I wasn't gonna specify which version of Perl throughout the book, because the book is devoted to Perl 6 only, _not_ Perl 5.

_Section 1.2 (Running Perl 6)_ states clearly:

_Compared to Perl 5, Perl 6 is not just a new version of Perl. It is more like the new little
sister of Perl 5. It does not aim at replacing Perl 5. Perl 6 is really a new programming
language, with a syntax that is similar to earlier versions of Perl (such as Perl 5), but still
markedly different. Unless stated otherwise, this book is about Perl 6 only, not about Perl 5
and preceding versions of the Perl programming language. **From now on, whenever we
speak about Perl with no further qualification, we mean Perl 6.**_

Now, admittedly, despite having said that very early in the book, I am still quite often specifying Perl 6 when there is a significant difference between P5 and P6 (for helping purposes, just to avoid possible confusions for the sake of people knowing P5), but, again, the book is about Perl 6, only Perl 6, and I don't expect anywhere people to know Perl 5.
