### ISSUE TITLE
functional.tex Feed and Backward Feed Operators has broken example code

### ISSUE THREAD

**Issue by zengargoyle** [LaurentRosenfeld/thinkperl6#6]
\begin{verbatim}
"id1;13-05-2015"-                                                               
    ==> split(/<[;-]>/)-                                                        
    ==> reverse()-                                                              
    ==> join(",")-                                                              
    ==> my @out;  # @out is now: [2015,05,13,id1]
\end{verbatim}

Should be ["2015,05,13,id1"] because of the join().  Or alternatively $out and "2015.05,13,id1" to match
the second example in the section.

**Comment by LaurentRosenfeld** [comment]
Hi,
it is true that @out is an array containing only one element that happens to be a string, because of the join. However, printing @out displays [2015,05,13,id1]:
say @out;       # [2015,05,13,id1]
So this is not really faulty. But, yes, it might me misunderstood as an array of four items.
We would need to use the perl method to display the quotes showing that is is a string:
say @out.perl;    # ["2015,05,13,id1"]
I guess I'll add a line using the perl method to make it clearer.

**Comment by LaurentRosenfeld** [comment]
Above mentioned change made.
