### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by Adrianzo** [LaurentRosenfeld/thinkperl6#7]
I see the repo has an MIT LICENSE but on the PDF you stated CC BY NC SA.

**Comment by LaurentRosenfeld** [comment]
Yes, you are right, thank you for telling me. This book is under Creative Commons Attribution-NonCommercial 3.0 Unported License, not the MIT License. 

I do not know how this MIT License got there, I probably made a mistake at some point. I guess the main difference is that anyone is entitled to do almost anything with this book, except republish or otherwise use it for commercial propose, which would violate the book's publisher's rights. I have duly changed it.
